### ISSUE TITLE
关于 BaseSwipeBackActivity 

### ISSUE THREAD

**Issue by ilpanda** [gzsll/TLint#1]
你好 
你的TLint项目中  使用了 BaseSwipeBackActivity  
但是并没有看到    你调用其相关的方法就实现了   所有 activity   右边进入退出动画  (类似ios效果)
我想问你怎么做到的

**Comment by ilpanda** [comment]
我同样 使用的了BaseSwipeBackActivity ,但是只有从屏幕边缘滑动的时候  从右边退出,按返回键并没有这样的效果

**Comment by gzsll** [comment]
滑动返回是基于`https://github.com/ikew0ng/SwipeBackLayout`这个项目实现的，你可以看下~~

**Comment by ilpanda** [comment]
谢谢你的回复  我已经解决了这个问题
