### ISSUE TITLE
Cookies

### ISSUE THREAD

**Issue by smuyyh** [gzsll/TLint#13]
你好，请问那个Cookies要怎么获取？这部分有点看不太懂~  应该是要模拟登录拿到cookies才可以进行评论回复这些东西吧？

**Comment by smuyyh** [comment]
还有就是评论的时候，都不成功，返回数据也是空的，但是有成功响应。token和sign的值应该都是对的，还会有其他什么原因呢？

**Comment by gzsll** [comment]
是的，要cookie才能评论这些操作，登录的时候先调用`GameApi`的login方法，如果登陆成功，会返回cookie，这时候可以通过`CookieInterceptor`来拦截和保存cookie
